export { agregaEstudiantesCurso, validaAprendizInscrito } from './funcion1.js';
export { calcularInventario } from './funcion2.js';
export { calcularPromedio } from './funcion3.js';
export { calcularProductos } from './funcion4.js';
export { validarUsuario } from './funcion5.js';
export { calcularNeto } from './funcion6.js';
export { registrarProductos } from './funcion7.js';
export { buscarCursos, filtrarPorCategoria, filtrarPorDuracion, filtrarPorNombre } from './funcion8.js';
export { procesarPagos, aprobarPorMonto, aprobarPorMetodo, aprobarPorFecha } from './funcion9.js';
export { fusionarUsuarios } from "./funcion10.js";
